trigger:
- main

pool:
  vmImage: 'windows-latest'

parameters:
- name: environment
  type: string
  default: 'dev'
  values:
  - dev
  - staging
  - production

variables:
  environment: ${{ parameters.environment }}

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: DeployJob
    displayName: Deploy Job
    steps:
    - checkout: self

    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: './deploy_script.ps1'
        arguments: '-Environment $(environment)'